--- 
- name: install httpd
  hosts: node1
  remote_user: ansible
  become: true
  tasks: 
  - name: install latest apache
    yum: 
     name: httpd
     state: latest
  - name: Lineinfile 
    lineinfile:
      path: /var/www/html/index.html
      line: 'This is from {{ ansible_hostname }}'
      create: yes
  - name: download configuration file
    get_url:
      url: http://control.example.com/configuration/httpd.conf.j2
      dest: /etc/httpd/conf.d/httpd.conf
  - name: service start
    service:
     name: httpd
     state: started
     enabled: yes
  - name: starting firewall
    firewalld:
     service: http
     state: enabled
     permanent: yes
     immediate: yes
    
